### ISSUE TITLE
Online-Offline Status

### ISSUE THREAD

**Issue by Satyajit-2003** [ajmaln/DRF-Chat#20]
The panel shows Offline even if the other user is online and constantly sending messaging

**Comment by ajmaln** [comment]
Hi, Make sure you have installed memcached.

On windows: https://stackoverflow.com/questions/59476616/install-memcached-on-windows

On Ubuntu:
```
sudo apt install memcached
```

**Comment by ajmaln** [comment]
I hope this resolves your issue. Closing.
