### ISSUE TITLE
The online-offline status doesn't work

### ISSUE THREAD

**Issue by ionecum** [ajmaln/DRF-Chat#31]
No way to get it to work. The self.last_seen() method in chat/models.py always returns None. Therefore users are always marked as offline. It seems that 

finally:
                cache.set('last_seen_%s' % current_user.username, now,
                        settings.USER_LASTSEEN_TIMEOUT)

in middleware.py never get hit.

**Comment by ajmaln** [comment]
@ionecum 

Make sure you have installed `memcached`.

```
sudo apt install memcached
```
