### ISSUE TITLE
How is memcache used?

### ISSUE THREAD

**Issue by SapneshNaik** [ajmaln/DRF-Chat#8]
Hi, You mention 

> This app uses memcached to store Users online status, So you will need to install it.

in your readme. Can you please explain how this works? because all I see is you've added memcached as a cache back-end in Settings.py

**Comment by ajmaln** [comment]
Hi sorry for the late reply. I was a bit busy.

I use a middleware to store the data to cache. You can check this here : https://github.com/ajmaln/DRF-Chat/blob/master/chat/middleware.py

In `settings.py` it's configured to use the memcached as the default cache backend.
